// Code generated by protoc-gen-go.
// source: bblwheel.proto
// DO NOT EDIT!

/*
Package bblwheel is a generated protocol buffer package.

It is generated from these files:
	bblwheel.proto
	rpc.proto

It has these top-level messages:
	Void
	RegisterResult
	Service
	ConfigEntry
	Config
	UpdateConfigReq
	Stats
	Event
	LookupConfigReq
	LookupConfigResp
	LookupServiceReq
	LookupServiceResp
	Request
	Response
	Message
*/
package bblwheel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service_Status int32

const (
	Service_INIT        Service_Status = 0
	Service_ONLINE      Service_Status = 1
	Service_MAINTENANCE Service_Status = 2
	Service_OFFLINE     Service_Status = 3
	Service_FAULT       Service_Status = 4
	Service_UNAUTHORIZE Service_Status = 5
)

var Service_Status_name = map[int32]string{
	0: "INIT",
	1: "ONLINE",
	2: "MAINTENANCE",
	3: "OFFLINE",
	4: "FAULT",
	5: "UNAUTHORIZE",
}
var Service_Status_value = map[string]int32{
	"INIT":        0,
	"ONLINE":      1,
	"MAINTENANCE": 2,
	"OFFLINE":     3,
	"FAULT":       4,
	"UNAUTHORIZE": 5,
}

func (x Service_Status) String() string {
	return proto.EnumName(Service_Status_name, int32(x))
}
func (Service_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Event_EventType int32

const (
	Event_DISCOVERY       Event_EventType = 0
	Event_CONFIGUPDATE    Event_EventType = 1
	Event_REGISTER_RESULT Event_EventType = 2
	Event_KEEPALIVE       Event_EventType = 3
	Event_CONTROL         Event_EventType = 4
	Event_EXEC            Event_EventType = 5
)

var Event_EventType_name = map[int32]string{
	0: "DISCOVERY",
	1: "CONFIGUPDATE",
	2: "REGISTER_RESULT",
	3: "KEEPALIVE",
	4: "CONTROL",
	5: "EXEC",
}
var Event_EventType_value = map[string]int32{
	"DISCOVERY":       0,
	"CONFIGUPDATE":    1,
	"REGISTER_RESULT": 2,
	"KEEPALIVE":       3,
	"CONTROL":         4,
	"EXEC":            5,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}
func (Event_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegisterResult struct {
	Desc    string             `protobuf:"bytes,1,opt,name=Desc" json:"Desc,omitempty"`
	Service []*Service         `protobuf:"bytes,2,rep,name=Service" json:"Service,omitempty"`
	Configs map[string]*Config `protobuf:"bytes,3,rep,name=Configs" json:"Configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RegisterResult) Reset()                    { *m = RegisterResult{} }
func (m *RegisterResult) String() string            { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()               {}
func (*RegisterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterResult) GetService() []*Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *RegisterResult) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Service struct {
	ID                string         `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name              string         `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Tags              []string       `protobuf:"bytes,3,rep,name=Tags" json:"Tags,omitempty"`
	Address           string         `protobuf:"bytes,4,opt,name=Address" json:"Address,omitempty"`
	DataCenter        string         `protobuf:"bytes,5,opt,name=DataCenter" json:"DataCenter,omitempty"`
	Node              string         `protobuf:"bytes,6,opt,name=Node" json:"Node,omitempty"`
	PID               string         `protobuf:"bytes,7,opt,name=PID" json:"PID,omitempty"`
	Weight            int32          `protobuf:"varint,8,opt,name=Weight" json:"Weight,omitempty"`
	Single            bool           `protobuf:"varint,9,opt,name=Single" json:"Single,omitempty"`
	DependentServices []string       `protobuf:"bytes,10,rep,name=DependentServices" json:"DependentServices,omitempty"`
	DependentConfigs  []string       `protobuf:"bytes,11,rep,name=DependentConfigs" json:"DependentConfigs,omitempty"`
	Status            Service_Status `protobuf:"varint,12,opt,name=status,enum=bblwheel.Service_Status" json:"status,omitempty"`
	Stats             *Stats         `protobuf:"bytes,13,opt,name=Stats" json:"Stats,omitempty"`
	Error             string         `protobuf:"bytes,14,opt,name=Error" json:"Error,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Service) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ConfigEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *ConfigEntry) Reset()                    { *m = ConfigEntry{} }
func (m *ConfigEntry) String() string            { return proto.CompactTextString(m) }
func (*ConfigEntry) ProtoMessage()               {}
func (*ConfigEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Config struct {
	Items []*ConfigEntry `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Config) GetItems() []*ConfigEntry {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateConfigReq struct {
	ServiceID   string  `protobuf:"bytes,1,opt,name=ServiceID" json:"ServiceID,omitempty"`
	ServiceName string  `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Config      *Config `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *UpdateConfigReq) Reset()                    { *m = UpdateConfigReq{} }
func (m *UpdateConfigReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigReq) ProtoMessage()               {}
func (*UpdateConfigReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateConfigReq) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type Stats struct {
	ServiceID      string            `protobuf:"bytes,1,opt,name=ServiceID" json:"ServiceID,omitempty"`
	ServiceName    string            `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Count          int64             `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	UpTime         int64             `protobuf:"varint,4,opt,name=UpTime" json:"UpTime,omitempty"`
	UsedMem        int64             `protobuf:"varint,5,opt,name=UsedMem" json:"UsedMem,omitempty"`
	FreeMem        int64             `protobuf:"varint,6,opt,name=FreeMem" json:"FreeMem,omitempty"`
	Threads        int64             `protobuf:"varint,7,opt,name=Threads" json:"Threads,omitempty"`
	AvgRespTime    int64             `protobuf:"varint,8,opt,name=AvgRespTime" json:"AvgRespTime,omitempty"`
	MinRespTime    int64             `protobuf:"varint,9,opt,name=MinRespTime" json:"MinRespTime,omitempty"`
	MaxRespTime    int64             `protobuf:"varint,10,opt,name=MaxRespTime" json:"MaxRespTime,omitempty"`
	LastActiveTime int64             `protobuf:"varint,11,opt,name=LastActiveTime" json:"LastActiveTime,omitempty"`
	Other          map[string]string `protobuf:"bytes,12,rep,name=Other" json:"Other,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Errors         string            `protobuf:"bytes,13,opt,name=Errors" json:"Errors,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Stats) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

type Event struct {
	Type    Event_EventType `protobuf:"varint,1,opt,name=Type,enum=bblwheel.Event_EventType" json:"Type,omitempty"`
	Service *Service        `protobuf:"bytes,2,opt,name=Service" json:"Service,omitempty"`
	Item    *ConfigEntry    `protobuf:"bytes,3,opt,name=Item" json:"Item,omitempty"`
	Command string          `protobuf:"bytes,4,opt,name=Command" json:"Command,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Event) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Event) GetItem() *ConfigEntry {
	if m != nil {
		return m.Item
	}
	return nil
}

type LookupConfigReq struct {
	DependentConfigs []string `protobuf:"bytes,1,rep,name=DependentConfigs" json:"DependentConfigs,omitempty"`
}

func (m *LookupConfigReq) Reset()                    { *m = LookupConfigReq{} }
func (m *LookupConfigReq) String() string            { return proto.CompactTextString(m) }
func (*LookupConfigReq) ProtoMessage()               {}
func (*LookupConfigReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LookupConfigResp struct {
	Configs map[string]*Config `protobuf:"bytes,1,rep,name=Configs" json:"Configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *LookupConfigResp) Reset()                    { *m = LookupConfigResp{} }
func (m *LookupConfigResp) String() string            { return proto.CompactTextString(m) }
func (*LookupConfigResp) ProtoMessage()               {}
func (*LookupConfigResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LookupConfigResp) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type LookupServiceReq struct {
	DependentServices []string `protobuf:"bytes,1,rep,name=DependentServices" json:"DependentServices,omitempty"`
}

func (m *LookupServiceReq) Reset()                    { *m = LookupServiceReq{} }
func (m *LookupServiceReq) String() string            { return proto.CompactTextString(m) }
func (*LookupServiceReq) ProtoMessage()               {}
func (*LookupServiceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type LookupServiceResp struct {
	Services []*Service `protobuf:"bytes,1,rep,name=Services" json:"Services,omitempty"`
}

func (m *LookupServiceResp) Reset()                    { *m = LookupServiceResp{} }
func (m *LookupServiceResp) String() string            { return proto.CompactTextString(m) }
func (*LookupServiceResp) ProtoMessage()               {}
func (*LookupServiceResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LookupServiceResp) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "bblwheel.Void")
	proto.RegisterType((*RegisterResult)(nil), "bblwheel.RegisterResult")
	proto.RegisterType((*Service)(nil), "bblwheel.Service")
	proto.RegisterType((*ConfigEntry)(nil), "bblwheel.ConfigEntry")
	proto.RegisterType((*Config)(nil), "bblwheel.Config")
	proto.RegisterType((*UpdateConfigReq)(nil), "bblwheel.UpdateConfigReq")
	proto.RegisterType((*Stats)(nil), "bblwheel.Stats")
	proto.RegisterType((*Event)(nil), "bblwheel.Event")
	proto.RegisterType((*LookupConfigReq)(nil), "bblwheel.LookupConfigReq")
	proto.RegisterType((*LookupConfigResp)(nil), "bblwheel.LookupConfigResp")
	proto.RegisterType((*LookupServiceReq)(nil), "bblwheel.LookupServiceReq")
	proto.RegisterType((*LookupServiceResp)(nil), "bblwheel.LookupServiceResp")
	proto.RegisterEnum("bblwheel.Service_Status", Service_Status_name, Service_Status_value)
	proto.RegisterEnum("bblwheel.Event_EventType", Event_EventType_name, Event_EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BblWheel service

type BblWheelClient interface {
	LookupConfig(ctx context.Context, in *LookupConfigReq, opts ...grpc.CallOption) (*LookupConfigResp, error)
	LookupService(ctx context.Context, in *LookupServiceReq, opts ...grpc.CallOption) (*LookupServiceResp, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*Void, error)
	Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegisterResult, error)
	Unregister(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error)
	Events(ctx context.Context, opts ...grpc.CallOption) (BblWheel_EventsClient, error)
}

type bblWheelClient struct {
	cc *grpc.ClientConn
}

func NewBblWheelClient(cc *grpc.ClientConn) BblWheelClient {
	return &bblWheelClient{cc}
}

func (c *bblWheelClient) LookupConfig(ctx context.Context, in *LookupConfigReq, opts ...grpc.CallOption) (*LookupConfigResp, error) {
	out := new(LookupConfigResp)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/LookupConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) LookupService(ctx context.Context, in *LookupServiceReq, opts ...grpc.CallOption) (*LookupServiceResp, error) {
	out := new(LookupServiceResp)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/LookupService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/UpdateConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegisterResult, error) {
	out := new(RegisterResult)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) Unregister(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/Unregister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) Events(ctx context.Context, opts ...grpc.CallOption) (BblWheel_EventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BblWheel_serviceDesc.Streams[0], c.cc, "/bblwheel.BblWheel/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &bblWheelEventsClient{stream}
	return x, nil
}

type BblWheel_EventsClient interface {
	Send(*Event) error
	Recv() (*Event, error)
	grpc.ClientStream
}

type bblWheelEventsClient struct {
	grpc.ClientStream
}

func (x *bblWheelEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bblWheelEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for BblWheel service

type BblWheelServer interface {
	LookupConfig(context.Context, *LookupConfigReq) (*LookupConfigResp, error)
	LookupService(context.Context, *LookupServiceReq) (*LookupServiceResp, error)
	UpdateConfig(context.Context, *UpdateConfigReq) (*Void, error)
	Register(context.Context, *Service) (*RegisterResult, error)
	Unregister(context.Context, *Service) (*Void, error)
	Events(BblWheel_EventsServer) error
}

func RegisterBblWheelServer(s *grpc.Server, srv BblWheelServer) {
	s.RegisterService(&_BblWheel_serviceDesc, srv)
}

func _BblWheel_LookupConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).LookupConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/LookupConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).LookupConfig(ctx, req.(*LookupConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_LookupService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupServiceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).LookupService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/LookupService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).LookupService(ctx, req.(*LookupServiceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).UpdateConfig(ctx, req.(*UpdateConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).Register(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).Unregister(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BblWheelServer).Events(&bblWheelEventsServer{stream})
}

type BblWheel_EventsServer interface {
	Send(*Event) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type bblWheelEventsServer struct {
	grpc.ServerStream
}

func (x *bblWheelEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bblWheelEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BblWheel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bblwheel.BblWheel",
	HandlerType: (*BblWheelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupConfig",
			Handler:    _BblWheel_LookupConfig_Handler,
		},
		{
			MethodName: "LookupService",
			Handler:    _BblWheel_LookupService_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _BblWheel_UpdateConfig_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _BblWheel_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _BblWheel_Unregister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _BblWheel_Events_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bblwheel.proto",
}

func init() { proto.RegisterFile("bblwheel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1050 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x56, 0xef, 0x6e, 0xe3, 0x44,
	0x10, 0x3f, 0xc7, 0xb1, 0x13, 0x4f, 0x72, 0x89, 0x3b, 0x14, 0xe4, 0xcb, 0x21, 0x14, 0x59, 0xba,
	0x23, 0x70, 0x5c, 0xa8, 0x8a, 0x4e, 0x1c, 0x48, 0x08, 0xd2, 0xc4, 0xbd, 0x5a, 0x4d, 0x93, 0x6a,
	0xe3, 0xf4, 0x0e, 0xbe, 0x20, 0xb7, 0x5e, 0xd2, 0xe8, 0x12, 0x3b, 0xb5, 0x9d, 0x42, 0xc5, 0x53,
	0xf0, 0x06, 0x48, 0x3c, 0x13, 0xdf, 0x79, 0x04, 0x3e, 0xf0, 0x00, 0x68, 0xd7, 0xeb, 0x3f, 0x4d,
	0x1b, 0xf8, 0x80, 0xc4, 0x97, 0x68, 0x67, 0x7e, 0xbf, 0xd9, 0x99, 0xdd, 0xfd, 0xcd, 0xc4, 0xd0,
	0x38, 0x3f, 0x5f, 0xfc, 0x78, 0x49, 0xe9, 0xa2, 0xbb, 0x0a, 0x83, 0x38, 0xc0, 0x6a, 0x6a, 0x9b,
	0x2a, 0x94, 0xcf, 0x82, 0xb9, 0x67, 0xfe, 0x21, 0x41, 0x83, 0xd0, 0xd9, 0x3c, 0x8a, 0x69, 0x48,
	0x68, 0xb4, 0x5e, 0xc4, 0x88, 0x50, 0x1e, 0xd0, 0xe8, 0xc2, 0x90, 0xda, 0x52, 0x47, 0x23, 0x7c,
	0x8d, 0xcf, 0xa0, 0x32, 0xa1, 0xe1, 0xf5, 0xfc, 0x82, 0x1a, 0xa5, 0xb6, 0xdc, 0xa9, 0xed, 0xef,
	0x74, 0xb3, 0xad, 0x05, 0x40, 0x52, 0x06, 0x7e, 0x0d, 0x95, 0x7e, 0xe0, 0xff, 0x30, 0x9f, 0x45,
	0x86, 0xcc, 0xc9, 0x4f, 0x72, 0xf2, 0xed, 0x5c, 0x5d, 0xc1, 0xb3, 0xfc, 0x38, 0xbc, 0x21, 0x69,
	0x54, 0x6b, 0x08, 0xf5, 0x22, 0x80, 0x3a, 0xc8, 0x6f, 0xe9, 0x8d, 0x28, 0x88, 0x2d, 0xf1, 0x29,
	0x28, 0xd7, 0xee, 0x62, 0xcd, 0xaa, 0x91, 0x3a, 0xb5, 0x7d, 0x3d, 0x4f, 0x90, 0x04, 0x92, 0x04,
	0xfe, 0xb2, 0xf4, 0x52, 0x32, 0xff, 0x92, 0xb3, 0xe2, 0xb1, 0x01, 0x25, 0x7b, 0x20, 0x36, 0x2a,
	0xd9, 0x03, 0x76, 0xd6, 0x91, 0xbb, 0x4c, 0xb6, 0xd1, 0x08, 0x5f, 0x33, 0x9f, 0xe3, 0x8a, 0xda,
	0x35, 0xc2, 0xd7, 0x68, 0x40, 0xa5, 0xe7, 0x79, 0x21, 0x8d, 0x22, 0xa3, 0xcc, 0xa9, 0xa9, 0x89,
	0x1f, 0x00, 0x0c, 0xdc, 0xd8, 0xed, 0x53, 0x3f, 0xa6, 0xa1, 0xa1, 0x70, 0xb0, 0xe0, 0xe1, 0x19,
	0x02, 0x8f, 0x1a, 0xaa, 0xc8, 0x10, 0x78, 0x94, 0x9d, 0xe7, 0xd4, 0x1e, 0x18, 0x95, 0xe4, 0x3c,
	0xa7, 0xf6, 0x00, 0xdf, 0x03, 0xf5, 0x35, 0x9d, 0xcf, 0x2e, 0x63, 0xa3, 0xda, 0x96, 0x3a, 0x0a,
	0x11, 0x16, 0xf3, 0x4f, 0xe6, 0xfe, 0x6c, 0x41, 0x0d, 0xad, 0x2d, 0x75, 0xaa, 0x44, 0x58, 0xf8,
	0x09, 0xec, 0x0c, 0xe8, 0x8a, 0xfa, 0x1e, 0xf5, 0x63, 0x71, 0xb6, 0xc8, 0x00, 0x5e, 0xf0, 0x5d,
	0x00, 0x3f, 0x06, 0x3d, 0x73, 0xa6, 0x2f, 0x53, 0xe3, 0xe4, 0x3b, 0x7e, 0xdc, 0x03, 0x35, 0x8a,
	0xdd, 0x78, 0x1d, 0x19, 0xf5, 0xb6, 0xd4, 0x69, 0xec, 0x1b, 0x77, 0x1e, 0xba, 0x3b, 0xe1, 0x38,
	0x11, 0x3c, 0x7c, 0x02, 0x0a, 0xf3, 0x44, 0xc6, 0x43, 0xfe, 0x16, 0xcd, 0x42, 0x00, 0x73, 0x93,
	0x04, 0xc5, 0x5d, 0x50, 0xac, 0x30, 0x0c, 0x42, 0xa3, 0xc1, 0x8f, 0x9d, 0x18, 0xe6, 0x1b, 0x50,
	0x93, 0xed, 0xb0, 0x0a, 0x65, 0x7b, 0x64, 0x3b, 0xfa, 0x03, 0x04, 0x50, 0xc7, 0xa3, 0xa1, 0x3d,
	0xb2, 0x74, 0x09, 0x9b, 0x50, 0x3b, 0xe9, 0xd9, 0x23, 0xc7, 0x1a, 0xf5, 0x46, 0x7d, 0x4b, 0x2f,
	0x61, 0x0d, 0x2a, 0xe3, 0xc3, 0x43, 0x8e, 0xca, 0xa8, 0x81, 0x72, 0xd8, 0x9b, 0x0e, 0x1d, 0xbd,
	0xcc, 0x88, 0xd3, 0x51, 0x6f, 0xea, 0x1c, 0x8d, 0x89, 0xfd, 0x9d, 0xa5, 0x2b, 0xe6, 0x0b, 0xa8,
	0x25, 0x67, 0xca, 0x34, 0x74, 0x9c, 0x6b, 0xe8, 0x98, 0xde, 0xb0, 0x82, 0xce, 0x32, 0x0d, 0x69,
	0x24, 0x31, 0xcc, 0x17, 0xa0, 0x26, 0x61, 0xf8, 0x0c, 0x14, 0x3b, 0xa6, 0xcb, 0xc8, 0x90, 0xb8,
	0x88, 0xdf, 0xdd, 0xd4, 0x58, 0x22, 0xda, 0x84, 0x63, 0xfe, 0x0c, 0xcd, 0xe9, 0xca, 0x73, 0x63,
	0x2a, 0xf4, 0x47, 0xaf, 0xf0, 0x7d, 0xd0, 0xc4, 0x8d, 0x65, 0x92, 0xcb, 0x1d, 0xd8, 0x86, 0x9a,
	0x30, 0x0a, 0x02, 0x2c, 0xba, 0xb0, 0x03, 0xea, 0x05, 0xdf, 0xcc, 0x90, 0xb7, 0x88, 0x5c, 0xe0,
	0xe6, 0xef, 0xb2, 0x78, 0x82, 0xff, 0x9c, 0x73, 0x17, 0x94, 0x7e, 0xb0, 0xf6, 0x63, 0x9e, 0x52,
	0x26, 0x89, 0xc1, 0x54, 0x38, 0x5d, 0x39, 0xf3, 0x25, 0xe5, 0xe2, 0x97, 0x89, 0xb0, 0x58, 0x57,
	0x4c, 0x23, 0xea, 0x9d, 0xd0, 0x25, 0x17, 0xbe, 0x4c, 0x52, 0x93, 0x21, 0x87, 0x21, 0xa5, 0x0c,
	0x51, 0x13, 0x44, 0x98, 0x0c, 0x71, 0x2e, 0x43, 0xea, 0x7a, 0x11, 0xd7, 0xbf, 0x4c, 0x52, 0x93,
	0x55, 0xd7, 0xbb, 0x9e, 0x11, 0x1a, 0x25, 0xa9, 0xaa, 0x1c, 0x2d, 0xba, 0x18, 0xe3, 0x64, 0xee,
	0x67, 0x0c, 0x2d, 0x61, 0x14, 0x5c, 0x9c, 0xe1, 0xfe, 0x94, 0x31, 0x40, 0x30, 0x72, 0x17, 0x3e,
	0x85, 0xc6, 0xd0, 0x8d, 0xe2, 0xde, 0x45, 0x3c, 0xbf, 0xa6, 0x9c, 0x54, 0xe3, 0xa4, 0x0d, 0x2f,
	0xee, 0x81, 0x32, 0x8e, 0x2f, 0x69, 0x68, 0xd4, 0xf9, 0xeb, 0xb7, 0x36, 0x54, 0xdd, 0xe5, 0xa0,
	0x90, 0x00, 0x5f, 0xb3, 0x5b, 0xe2, 0x9a, 0x4e, 0x1a, 0x41, 0x23, 0xc2, 0x6a, 0xbd, 0x04, 0xc8,
	0xc9, 0xf7, 0xcc, 0xb2, 0xdd, 0xe2, 0x2c, 0xd3, 0x8a, 0x93, 0xeb, 0x97, 0x12, 0x28, 0xd6, 0x35,
	0xf5, 0x63, 0x7c, 0x0e, 0x65, 0xe7, 0x66, 0x45, 0x79, 0x58, 0x63, 0xff, 0x51, 0x5e, 0x0c, 0x87,
	0x93, 0x5f, 0x46, 0x20, 0x9c, 0x76, 0x7b, 0x5c, 0x4b, 0xff, 0x32, 0xae, 0x3f, 0x82, 0x32, 0xd3,
	0xb0, 0x50, 0xd9, 0x16, 0x99, 0x73, 0x0a, 0x7b, 0xbc, 0x7e, 0xb0, 0x5c, 0xba, 0xbe, 0x97, 0x8e,
	0x41, 0x61, 0x9a, 0x33, 0xd0, 0xb2, 0x22, 0xf0, 0x21, 0x68, 0x03, 0x7b, 0xd2, 0x1f, 0x9f, 0x59,
	0xe4, 0x5b, 0xfd, 0x01, 0xea, 0x50, 0xef, 0x8f, 0x47, 0x87, 0xf6, 0xab, 0xe9, 0xe9, 0xa0, 0xe7,
	0xb0, 0xae, 0x7e, 0x07, 0x9a, 0xc4, 0x7a, 0x65, 0x4f, 0x1c, 0x8b, 0x7c, 0x4f, 0xac, 0x09, 0xeb,
	0xe0, 0x12, 0x8b, 0x3a, 0xb6, 0xac, 0xd3, 0xde, 0xd0, 0x3e, 0x63, 0xbd, 0x5d, 0x83, 0x4a, 0x7f,
	0x3c, 0x72, 0xc8, 0x78, 0xa8, 0x97, 0xd9, 0x70, 0xb0, 0xde, 0x58, 0x7d, 0x5d, 0x31, 0xbf, 0x82,
	0xe6, 0x30, 0x08, 0xde, 0xae, 0x57, 0x79, 0xa3, 0xdd, 0x37, 0xde, 0xa4, 0xfb, 0xc7, 0x9b, 0xf9,
	0x9b, 0x04, 0xfa, 0xed, 0xf8, 0x68, 0x85, 0xbd, 0xfc, 0x0f, 0x2b, 0xe9, 0xf5, 0x0f, 0xf3, 0x4b,
	0xd8, 0x24, 0xff, 0x2f, 0x7f, 0x59, 0xdf, 0xa4, 0x45, 0xa6, 0x8f, 0x45, 0xaf, 0xee, 0x1f, 0xf9,
	0xd2, 0x96, 0x91, 0x6f, 0x1e, 0xc0, 0xce, 0xc6, 0x0e, 0xd1, 0x0a, 0x9f, 0x43, 0xf5, 0x56, 0xe4,
	0xbd, 0xba, 0xc8, 0x28, 0xfb, 0x7f, 0x96, 0xa0, 0x7a, 0x70, 0xbe, 0x78, 0xcd, 0x60, 0xb4, 0xa0,
	0x5e, 0xbc, 0x0a, 0x7c, 0xb4, 0xed, 0x8a, 0xae, 0x5a, 0xad, 0xed, 0xb7, 0x87, 0x47, 0xf0, 0xf0,
	0x56, 0x5d, 0x78, 0x87, 0x9c, 0x1f, 0xb9, 0xf5, 0x78, 0x2b, 0x16, 0xad, 0xf0, 0x0b, 0xa8, 0x17,
	0x27, 0x6e, 0xb1, 0xa0, 0x8d, 0x49, 0xdc, 0x6a, 0xe4, 0x10, 0xfb, 0xe8, 0xc1, 0xcf, 0xa1, 0x9a,
	0x7e, 0x87, 0xe0, 0xdd, 0x1b, 0x68, 0x19, 0xdb, 0x3e, 0x57, 0xf0, 0x53, 0x80, 0xa9, 0x1f, 0xfe,
	0x43, 0xe8, 0x66, 0xa6, 0x2e, 0xa8, 0xbc, 0x2d, 0x22, 0x6c, 0x6e, 0xf4, 0x6c, 0x6b, 0xd3, 0xd1,
	0x91, 0xf6, 0xa4, 0x83, 0xc7, 0xb0, 0x7b, 0x11, 0x2c, 0xbb, 0x97, 0x74, 0xe9, 0xde, 0xac, 0xfd,
	0x8c, 0x71, 0x24, 0xfd, 0x2a, 0x49, 0xe7, 0x2a, 0xff, 0x88, 0xfb, 0xec, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0x2b, 0x51, 0x1a, 0xd6, 0x09, 0x00, 0x00,
}
