// Code generated by protoc-gen-go.
// source: bblwheel.proto
// DO NOT EDIT!

/*
Package bblwheel is a generated protocol buffer package.

It is generated from these files:
	bblwheel.proto
	rpc.proto

It has these top-level messages:
	Void
	Service
	ConfigEntry
	Config
	UpdateConfigReq
	Stats
	Event
	Request
	Response
	Message
*/
package bblwheel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service_Status int32

const (
	Service_INIT        Service_Status = 0
	Service_ONLINE      Service_Status = 1
	Service_MAINTENANCE Service_Status = 2
	Service_OFFLINE     Service_Status = 3
	Service_FAULT       Service_Status = 4
	Service_UNAUTHORIZE Service_Status = 5
)

var Service_Status_name = map[int32]string{
	0: "INIT",
	1: "ONLINE",
	2: "MAINTENANCE",
	3: "OFFLINE",
	4: "FAULT",
	5: "UNAUTHORIZE",
}
var Service_Status_value = map[string]int32{
	"INIT":        0,
	"ONLINE":      1,
	"MAINTENANCE": 2,
	"OFFLINE":     3,
	"FAULT":       4,
	"UNAUTHORIZE": 5,
}

func (x Service_Status) String() string {
	return proto.EnumName(Service_Status_name, int32(x))
}
func (Service_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Event_EventType int32

const (
	Event_DISCOVERY       Event_EventType = 0
	Event_CONFIGUPDATE    Event_EventType = 1
	Event_REGISTER_RESULT Event_EventType = 2
	Event_KEEPALIVE       Event_EventType = 3
)

var Event_EventType_name = map[int32]string{
	0: "DISCOVERY",
	1: "CONFIGUPDATE",
	2: "REGISTER_RESULT",
	3: "KEEPALIVE",
}
var Event_EventType_value = map[string]int32{
	"DISCOVERY":       0,
	"CONFIGUPDATE":    1,
	"REGISTER_RESULT": 2,
	"KEEPALIVE":       3,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}
func (Event_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Service struct {
	ID                string         `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name              string         `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Tags              []string       `protobuf:"bytes,3,rep,name=Tags" json:"Tags,omitempty"`
	Address           string         `protobuf:"bytes,4,opt,name=Address" json:"Address,omitempty"`
	DataCenter        string         `protobuf:"bytes,5,opt,name=DataCenter" json:"DataCenter,omitempty"`
	Node              string         `protobuf:"bytes,6,opt,name=Node" json:"Node,omitempty"`
	PID               string         `protobuf:"bytes,7,opt,name=PID" json:"PID,omitempty"`
	Weight            int32          `protobuf:"varint,8,opt,name=Weight" json:"Weight,omitempty"`
	Single            bool           `protobuf:"varint,9,opt,name=Single" json:"Single,omitempty"`
	DependentServices []string       `protobuf:"bytes,10,rep,name=DependentServices" json:"DependentServices,omitempty"`
	DependentConfigs  []string       `protobuf:"bytes,11,rep,name=DependentConfigs" json:"DependentConfigs,omitempty"`
	Status            Service_Status `protobuf:"varint,12,opt,name=status,enum=bblwheel.Service_Status" json:"status,omitempty"`
	Stats             *Stats         `protobuf:"bytes,13,opt,name=Stats" json:"Stats,omitempty"`
	Error             string         `protobuf:"bytes,14,opt,name=Error" json:"Error,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Service) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ConfigEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *ConfigEntry) Reset()                    { *m = ConfigEntry{} }
func (m *ConfigEntry) String() string            { return proto.CompactTextString(m) }
func (*ConfigEntry) ProtoMessage()               {}
func (*ConfigEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Config struct {
	Items []*ConfigEntry `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Config) GetItems() []*ConfigEntry {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateConfigReq struct {
	ServiceID   string  `protobuf:"bytes,1,opt,name=ServiceID" json:"ServiceID,omitempty"`
	ServiceName string  `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Config      *Config `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *UpdateConfigReq) Reset()                    { *m = UpdateConfigReq{} }
func (m *UpdateConfigReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigReq) ProtoMessage()               {}
func (*UpdateConfigReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateConfigReq) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type Stats struct {
	ServiceID      string            `protobuf:"bytes,1,opt,name=ServiceID" json:"ServiceID,omitempty"`
	ServiceName    string            `protobuf:"bytes,2,opt,name=ServiceName" json:"ServiceName,omitempty"`
	Count          int64             `protobuf:"varint,3,opt,name=Count" json:"Count,omitempty"`
	UpTime         int64             `protobuf:"varint,4,opt,name=UpTime" json:"UpTime,omitempty"`
	UsedMem        int64             `protobuf:"varint,5,opt,name=UsedMem" json:"UsedMem,omitempty"`
	FreeMem        int64             `protobuf:"varint,6,opt,name=FreeMem" json:"FreeMem,omitempty"`
	Threads        int64             `protobuf:"varint,7,opt,name=Threads" json:"Threads,omitempty"`
	AvgRespTime    int64             `protobuf:"varint,8,opt,name=AvgRespTime" json:"AvgRespTime,omitempty"`
	MinRespTime    int64             `protobuf:"varint,9,opt,name=MinRespTime" json:"MinRespTime,omitempty"`
	MaxRespTime    int64             `protobuf:"varint,10,opt,name=MaxRespTime" json:"MaxRespTime,omitempty"`
	LastActiveTime int64             `protobuf:"varint,11,opt,name=LastActiveTime" json:"LastActiveTime,omitempty"`
	Other          map[string]string `protobuf:"bytes,12,rep,name=Other" json:"Other,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Stats) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

type Event struct {
	Type    Event_EventType    `protobuf:"varint,1,opt,name=Type,enum=bblwheel.Event_EventType" json:"Type,omitempty"`
	Service []*Service         `protobuf:"bytes,2,rep,name=Service" json:"Service,omitempty"`
	Item    *ConfigEntry       `protobuf:"bytes,3,opt,name=Item" json:"Item,omitempty"`
	Configs map[string]*Config `protobuf:"bytes,4,rep,name=Configs" json:"Configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Desc    string             `protobuf:"bytes,5,opt,name=Desc" json:"Desc,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Event) GetService() []*Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Event) GetItem() *ConfigEntry {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Event) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

func init() {
	proto.RegisterType((*Void)(nil), "bblwheel.Void")
	proto.RegisterType((*Service)(nil), "bblwheel.Service")
	proto.RegisterType((*ConfigEntry)(nil), "bblwheel.ConfigEntry")
	proto.RegisterType((*Config)(nil), "bblwheel.Config")
	proto.RegisterType((*UpdateConfigReq)(nil), "bblwheel.UpdateConfigReq")
	proto.RegisterType((*Stats)(nil), "bblwheel.Stats")
	proto.RegisterType((*Event)(nil), "bblwheel.Event")
	proto.RegisterEnum("bblwheel.Service_Status", Service_Status_name, Service_Status_value)
	proto.RegisterEnum("bblwheel.Event_EventType", Event_EventType_name, Event_EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BblWheel service

type BblWheelClient interface {
	Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (BblWheel_RegisterClient, error)
	Unregister(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error)
	Online(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error)
	UpdateStatus(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*Void, error)
}

type bblWheelClient struct {
	cc *grpc.ClientConn
}

func NewBblWheelClient(cc *grpc.ClientConn) BblWheelClient {
	return &bblWheelClient{cc}
}

func (c *bblWheelClient) Register(ctx context.Context, in *Service, opts ...grpc.CallOption) (BblWheel_RegisterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BblWheel_serviceDesc.Streams[0], c.cc, "/bblwheel.BblWheel/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &bblWheelRegisterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BblWheel_RegisterClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type bblWheelRegisterClient struct {
	grpc.ClientStream
}

func (x *bblWheelRegisterClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bblWheelClient) Unregister(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/Unregister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) Online(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/Online", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) UpdateStatus(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/UpdateStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bblWheelClient) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/bblwheel.BblWheel/UpdateConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BblWheel service

type BblWheelServer interface {
	Register(*Service, BblWheel_RegisterServer) error
	Unregister(context.Context, *Service) (*Void, error)
	Online(context.Context, *Service) (*Void, error)
	UpdateStatus(context.Context, *Service) (*Void, error)
	UpdateConfig(context.Context, *UpdateConfigReq) (*Void, error)
}

func RegisterBblWheelServer(s *grpc.Server, srv BblWheelServer) {
	s.RegisterService(&_BblWheel_serviceDesc, srv)
}

func _BblWheel_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Service)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BblWheelServer).Register(m, &bblWheelRegisterServer{stream})
}

type BblWheel_RegisterServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type bblWheelRegisterServer struct {
	grpc.ServerStream
}

func (x *bblWheelRegisterServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _BblWheel_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).Unregister(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_Online_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).Online(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/Online",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).Online(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).UpdateStatus(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _BblWheel_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BblWheelServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bblwheel.BblWheel/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BblWheelServer).UpdateConfig(ctx, req.(*UpdateConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BblWheel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bblwheel.BblWheel",
	HandlerType: (*BblWheelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unregister",
			Handler:    _BblWheel_Unregister_Handler,
		},
		{
			MethodName: "Online",
			Handler:    _BblWheel_Online_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _BblWheel_UpdateStatus_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _BblWheel_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _BblWheel_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bblwheel.proto",
}

func init() { proto.RegisterFile("bblwheel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 885 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x8e, 0xdb, 0x44,
	0x14, 0xad, 0xed, 0xd8, 0x49, 0x6e, 0xd2, 0xc4, 0x1d, 0x16, 0x34, 0x2c, 0x15, 0x8a, 0x22, 0x51,
	0x05, 0x16, 0xc2, 0x12, 0x54, 0x54, 0x78, 0x73, 0x13, 0xa7, 0xb5, 0x9a, 0x75, 0x56, 0x13, 0x67,
	0x0b, 0xbc, 0x20, 0x6f, 0x7c, 0x49, 0xac, 0x26, 0x76, 0xb0, 0xbd, 0x81, 0x15, 0x3f, 0xc0, 0x67,
	0xf0, 0x23, 0xfc, 0x15, 0x4f, 0x3c, 0xa1, 0x19, 0x4f, 0x1c, 0x2b, 0x5b, 0xd0, 0x4a, 0x7d, 0x89,
	0xe6, 0x9e, 0x73, 0xee, 0xdc, 0x99, 0x3b, 0x27, 0xd7, 0xd0, 0xba, 0xbe, 0x5e, 0xff, 0xba, 0x42,
	0x5c, 0xf7, 0xb7, 0x49, 0x9c, 0xc5, 0xa4, 0xb6, 0x8f, 0xbb, 0x06, 0x54, 0xae, 0xe2, 0x30, 0xe8,
	0xfe, 0xad, 0x41, 0x75, 0x86, 0xc9, 0x2e, 0x5c, 0x20, 0x69, 0x81, 0xea, 0x8c, 0xa8, 0xd2, 0x51,
	0x7a, 0x75, 0xa6, 0x3a, 0x23, 0x42, 0xa0, 0xe2, 0xfa, 0x1b, 0xa4, 0xaa, 0x40, 0xc4, 0x9a, 0x63,
	0x9e, 0xbf, 0x4c, 0xa9, 0xd6, 0xd1, 0x38, 0xc6, 0xd7, 0x84, 0x42, 0xd5, 0x0a, 0x82, 0x04, 0xd3,
	0x94, 0x56, 0x84, 0x74, 0x1f, 0x92, 0x8f, 0x01, 0x46, 0x7e, 0xe6, 0x0f, 0x31, 0xca, 0x30, 0xa1,
	0xba, 0x20, 0x4b, 0x88, 0xa8, 0x10, 0x07, 0x48, 0x0d, 0x59, 0x21, 0x0e, 0x90, 0x98, 0xa0, 0x5d,
	0x3a, 0x23, 0x5a, 0x15, 0x10, 0x5f, 0x92, 0x0f, 0xc0, 0x78, 0x8d, 0xe1, 0x72, 0x95, 0xd1, 0x5a,
	0x47, 0xe9, 0xe9, 0x4c, 0x46, 0x1c, 0x9f, 0x85, 0xd1, 0x72, 0x8d, 0xb4, 0xde, 0x51, 0x7a, 0x35,
	0x26, 0x23, 0xf2, 0x39, 0x3c, 0x1a, 0xe1, 0x16, 0xa3, 0x00, 0xa3, 0x4c, 0xde, 0x2d, 0xa5, 0x20,
	0x0e, 0x7c, 0x97, 0x20, 0x9f, 0x81, 0x59, 0x80, 0xc3, 0x38, 0xfa, 0x39, 0x5c, 0xa6, 0xb4, 0x21,
	0xc4, 0x77, 0x70, 0x72, 0x0e, 0x46, 0x9a, 0xf9, 0xd9, 0x4d, 0x4a, 0x9b, 0x1d, 0xa5, 0xd7, 0x1a,
	0xd0, 0x7e, 0xd1, 0x60, 0xb9, 0x5f, 0x7f, 0x26, 0x78, 0x26, 0x75, 0xe4, 0x13, 0xd0, 0x39, 0x92,
	0xd2, 0x87, 0x1d, 0xa5, 0xd7, 0x18, 0xb4, 0x4b, 0x09, 0x1c, 0x66, 0x39, 0x4b, 0x4e, 0x40, 0xb7,
	0x93, 0x24, 0x4e, 0x68, 0x4b, 0x5c, 0x3b, 0x0f, 0xba, 0xdf, 0x83, 0x91, 0x6f, 0x47, 0x6a, 0x50,
	0x71, 0x5c, 0xc7, 0x33, 0x1f, 0x10, 0x00, 0x63, 0xea, 0x4e, 0x1c, 0xd7, 0x36, 0x15, 0xd2, 0x86,
	0xc6, 0x85, 0xe5, 0xb8, 0x9e, 0xed, 0x5a, 0xee, 0xd0, 0x36, 0x55, 0xd2, 0x80, 0xea, 0x74, 0x3c,
	0x16, 0xac, 0x46, 0xea, 0xa0, 0x8f, 0xad, 0xf9, 0xc4, 0x33, 0x2b, 0x5c, 0x38, 0x77, 0xad, 0xb9,
	0xf7, 0x72, 0xca, 0x9c, 0x1f, 0x6d, 0x53, 0xef, 0x3e, 0x85, 0x46, 0x7e, 0x27, 0x3b, 0xca, 0x92,
	0x5b, 0xde, 0xf3, 0x57, 0x78, 0x2b, 0x9f, 0x9e, 0x2f, 0xf9, 0x81, 0xae, 0xfc, 0xf5, 0xcd, 0xfe,
	0xf1, 0xf3, 0xa0, 0xfb, 0x14, 0x8c, 0x3c, 0x8d, 0x9c, 0x81, 0xee, 0x64, 0xb8, 0x49, 0xa9, 0xd2,
	0xd1, 0x7a, 0x8d, 0xc1, 0xfb, 0x87, 0x7b, 0x95, 0xf6, 0x65, 0xb9, 0xa6, 0xfb, 0x3b, 0xb4, 0xe7,
	0xdb, 0xc0, 0xcf, 0x30, 0xe7, 0x18, 0xfe, 0x42, 0x1e, 0x43, 0x5d, 0x76, 0xac, 0xb0, 0xdc, 0x01,
	0x20, 0x1d, 0x68, 0xc8, 0xa0, 0x64, 0xc0, 0x32, 0x44, 0x7a, 0x60, 0x2c, 0xc4, 0x66, 0x54, 0x13,
	0x8d, 0x35, 0x8f, 0x0f, 0xc0, 0x24, 0xdf, 0xfd, 0x4b, 0x93, 0x4f, 0xf0, 0xce, 0x35, 0x4f, 0x40,
	0x1f, 0xc6, 0x37, 0x51, 0x26, 0x4a, 0x6a, 0x2c, 0x0f, 0xb8, 0x0b, 0xe7, 0x5b, 0x2f, 0xdc, 0xa0,
	0x30, 0xbf, 0xc6, 0x64, 0xc4, 0xff, 0x15, 0xf3, 0x14, 0x83, 0x0b, 0xdc, 0x08, 0xe3, 0x6b, 0x6c,
	0x1f, 0x72, 0x66, 0x9c, 0x20, 0x72, 0xc6, 0xc8, 0x19, 0x19, 0x72, 0xc6, 0x5b, 0x25, 0xe8, 0x07,
	0xa9, 0xf0, 0xbf, 0xc6, 0xf6, 0x21, 0x3f, 0x9d, 0xb5, 0x5b, 0x32, 0x4c, 0xf3, 0x52, 0x35, 0xc1,
	0x96, 0x21, 0xae, 0xb8, 0x08, 0xa3, 0x42, 0x51, 0xcf, 0x15, 0x25, 0x48, 0x28, 0xfc, 0xdf, 0x0a,
	0x05, 0x48, 0xc5, 0x01, 0x22, 0x4f, 0xa0, 0x35, 0xf1, 0xd3, 0xcc, 0x5a, 0x64, 0xe1, 0x0e, 0x85,
	0xa8, 0x21, 0x44, 0x47, 0x28, 0x39, 0x07, 0x7d, 0x9a, 0xad, 0x30, 0xa1, 0x4d, 0xf1, 0xfa, 0xa7,
	0x47, 0xae, 0xee, 0x0b, 0x52, 0x5a, 0x40, 0xac, 0x4f, 0x9f, 0x01, 0x1c, 0x40, 0xee, 0xb7, 0x37,
	0x07, 0xbf, 0xbd, 0xc9, 0xfd, 0xb6, 0x2b, 0xfb, 0x4d, 0x04, 0xdf, 0xa9, 0xcf, 0x94, 0xee, 0x3f,
	0x2a, 0xe8, 0xf6, 0x0e, 0xa3, 0x8c, 0x7c, 0x01, 0x15, 0xef, 0x76, 0x8b, 0x22, 0xad, 0x35, 0xf8,
	0xf0, 0x50, 0x54, 0xd0, 0xf9, 0x2f, 0x17, 0x30, 0x21, 0x23, 0x67, 0xc5, 0x64, 0xa3, 0xaa, 0x38,
	0xe6, 0xa3, 0x3b, 0xff, 0x56, 0x56, 0xcc, 0xbe, 0x4f, 0xa1, 0xc2, 0xbd, 0x2a, 0xdd, 0xf4, 0x1f,
	0x76, 0x16, 0x12, 0xf2, 0x0d, 0x54, 0xf7, 0x73, 0xa2, 0x22, 0xf6, 0x7d, 0x7c, 0x7c, 0x12, 0x49,
	0xe7, 0x49, 0x7b, 0x31, 0x1f, 0x76, 0x23, 0x4c, 0x17, 0x72, 0x0c, 0x8a, 0xf5, 0xe9, 0x04, 0x9a,
	0x65, 0xf1, 0x5b, 0x1a, 0xf3, 0xa4, 0xdc, 0x98, 0xb7, 0xf9, 0xbc, 0xd4, 0xaa, 0x4b, 0xa8, 0x17,
	0x4d, 0x20, 0x0f, 0xa1, 0x3e, 0x72, 0x66, 0xc3, 0xe9, 0x95, 0xcd, 0x7e, 0x30, 0x1f, 0x10, 0x13,
	0x9a, 0xc3, 0xa9, 0x3b, 0x76, 0x5e, 0xcc, 0x2f, 0x47, 0x96, 0xc7, 0xa7, 0xc7, 0x7b, 0xd0, 0x66,
	0xf6, 0x0b, 0x67, 0xe6, 0xd9, 0xec, 0x27, 0x66, 0xcf, 0xf8, 0xa4, 0x50, 0x79, 0xd6, 0x2b, 0xdb,
	0xbe, 0xb4, 0x26, 0xce, 0x95, 0x6d, 0x6a, 0x83, 0x3f, 0x54, 0xa8, 0x3d, 0xbf, 0x5e, 0xbf, 0xe6,
	0x05, 0xc9, 0x39, 0xd4, 0x18, 0x2e, 0xc3, 0x94, 0x4f, 0xee, 0xbb, 0xbd, 0x3c, 0x6d, 0x1f, 0xb5,
	0xe1, 0x5c, 0x21, 0x5f, 0x02, 0xcc, 0xa3, 0xe4, 0x7f, 0x72, 0x5a, 0x07, 0x88, 0x7f, 0x8e, 0xc8,
	0x19, 0x18, 0xd3, 0x68, 0x1d, 0x46, 0x78, 0x1f, 0xf1, 0x57, 0xd0, 0xcc, 0xc7, 0x8a, 0x1c, 0x92,
	0xf7, 0x48, 0xf9, 0x76, 0x9f, 0x22, 0xc7, 0x58, 0xc9, 0x44, 0x47, 0x13, 0xea, 0x38, 0xf5, 0xf9,
	0x47, 0x70, 0xb2, 0x88, 0x37, 0xfd, 0x15, 0x6e, 0xfc, 0xdb, 0x9b, 0xa8, 0x20, 0x5f, 0x2a, 0x7f,
	0x2a, 0xca, 0xb5, 0x21, 0xbe, 0xaf, 0x5f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x86, 0xe4, 0xed,
	0x39, 0x71, 0x07, 0x00, 0x00,
}
