// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Request
	Response
	Message
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	ID         int64             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	ClientID   string            `protobuf:"bytes,2,opt,name=ClientID" json:"ClientID,omitempty"`
	ClientAddr string            `protobuf:"bytes,3,opt,name=ClientAddr" json:"ClientAddr,omitempty"`
	Timestamp  int64             `protobuf:"varint,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
	ForwardFor []string          `protobuf:"bytes,5,rep,name=ForwardFor" json:"ForwardFor,omitempty"`
	Path       string            `protobuf:"bytes,6,opt,name=Path" json:"Path,omitempty"`
	Token      string            `protobuf:"bytes,7,opt,name=Token" json:"Token,omitempty"`
	Content    []byte            `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`
	Params     map[string]string `protobuf:"bytes,9,rep,name=Params" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Response struct {
	ID         int64             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	ClientID   string            `protobuf:"bytes,2,opt,name=ClientID" json:"ClientID,omitempty"`
	Timestamp  int64             `protobuf:"varint,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Status     int32             `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	StatusText string            `protobuf:"bytes,6,opt,name=StatusText" json:"StatusText,omitempty"`
	NewToken   string            `protobuf:"bytes,7,opt,name=NewToken" json:"NewToken,omitempty"`
	Content    []byte            `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`
	Params     map[string]string `protobuf:"bytes,9,rep,name=Params" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type Message struct {
	ID         int64             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Path       string            `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	Timestamp  int64             `protobuf:"varint,3,opt,name=Timestamp" json:"Timestamp,omitempty"`
	ForwardFor []string          `protobuf:"bytes,4,rep,name=ForwardFor" json:"ForwardFor,omitempty"`
	Token      string            `protobuf:"bytes,5,opt,name=Token" json:"Token,omitempty"`
	Content    []byte            `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	Params     map[string]string `protobuf:"bytes,7,rep,name=Params" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterType((*Response)(nil), "rpc.Response")
	proto.RegisterType((*Message)(nil), "rpc.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rpc service

type RpcClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Channel(ctx context.Context, opts ...grpc.CallOption) (Rpc_ChannelClient, error)
}

type rpcClient struct {
	cc *grpc.ClientConn
}

func NewRpcClient(cc *grpc.ClientConn) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/rpc.Rpc/Call", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) Channel(ctx context.Context, opts ...grpc.CallOption) (Rpc_ChannelClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Rpc_serviceDesc.Streams[0], c.cc, "/rpc.Rpc/Channel", opts...)
	if err != nil {
		return nil, err
	}
	x := &rpcChannelClient{stream}
	return x, nil
}

type Rpc_ChannelClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type rpcChannelClient struct {
	grpc.ClientStream
}

func (x *rpcChannelClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rpcChannelClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Rpc service

type RpcServer interface {
	Call(context.Context, *Request) (*Response, error)
	Channel(Rpc_ChannelServer) error
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RpcServer).Channel(&rpcChannelServer{stream})
}

type Rpc_ChannelServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type rpcChannelServer struct {
	grpc.ServerStream
}

func (x *rpcChannelServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rpcChannelServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Rpc_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _Rpc_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xe5, 0xa4, 0x49, 0x9a, 0xb3, 0x81, 0x90, 0x85, 0x90, 0xa9, 0x10, 0x44, 0xe3, 0x26,
	0xdc, 0x44, 0x63, 0xdc, 0x00, 0x77, 0xd0, 0x32, 0xd1, 0x0b, 0xd0, 0x64, 0xca, 0x03, 0xb8, 0xed,
	0x11, 0x9d, 0x96, 0xd8, 0xc1, 0x76, 0x29, 0x7d, 0x03, 0x1e, 0x83, 0x47, 0xe0, 0x21, 0x78, 0x30,
	0xe4, 0xc4, 0xed, 0x92, 0x4d, 0x9b, 0x84, 0xb4, 0xbb, 0xf3, 0x7d, 0xfe, 0x13, 0x9f, 0xdf, 0xf9,
	0x14, 0x48, 0x75, 0xbd, 0x28, 0x6a, 0xad, 0xac, 0xa2, 0xa1, 0xae, 0x17, 0x47, 0x7f, 0x03, 0x48,
	0x38, 0x7e, 0x5f, 0xa3, 0xb1, 0xf4, 0x3e, 0x04, 0xd3, 0x09, 0x23, 0x19, 0xc9, 0x43, 0x1e, 0x4c,
	0x27, 0x74, 0x04, 0xc3, 0x71, 0x79, 0x8e, 0xd2, 0x4e, 0x27, 0x2c, 0xc8, 0x48, 0x9e, 0xf2, 0xbd,
	0xa6, 0x4f, 0x01, 0xda, 0xfa, 0xdd, 0x72, 0xa9, 0x59, 0xd8, 0xac, 0x76, 0x1c, 0xfa, 0x04, 0xd2,
	0xd9, 0x79, 0x85, 0xc6, 0x8a, 0xaa, 0x66, 0x83, 0xe6, 0xca, 0x4b, 0xc3, 0x9d, 0x3e, 0x55, 0x7a,
	0x23, 0xf4, 0xf2, 0x54, 0x69, 0x16, 0x65, 0xa1, 0x3b, 0x7d, 0xe9, 0x50, 0x0a, 0x83, 0x33, 0x61,
	0x57, 0x2c, 0x6e, 0xee, 0x6d, 0x6a, 0xfa, 0x10, 0xa2, 0x99, 0xba, 0x40, 0xc9, 0x92, 0xc6, 0x6c,
	0x05, 0x65, 0x90, 0x8c, 0x95, 0xb4, 0x28, 0x2d, 0x1b, 0x66, 0x24, 0x3f, 0xe4, 0x3b, 0x49, 0x8f,
	0x21, 0x3e, 0x13, 0x5a, 0x54, 0x86, 0xa5, 0x59, 0x98, 0x1f, 0x9c, 0xb0, 0xc2, 0xb5, 0xee, 0x7b,
	0x2d, 0xda, 0xa5, 0x0f, 0xd2, 0xea, 0x2d, 0xf7, 0xfb, 0x46, 0x6f, 0xe0, 0xa0, 0x63, 0xd3, 0x07,
	0x10, 0x5e, 0xe0, 0xb6, 0xe1, 0x91, 0x72, 0x57, 0xba, 0x27, 0xfc, 0x10, 0xe5, 0x1a, 0x3d, 0x8d,
	0x56, 0xbc, 0x0d, 0x5e, 0x93, 0xa3, 0x3f, 0x01, 0x0c, 0x39, 0x9a, 0x5a, 0x49, 0x83, 0xff, 0xc5,
	0xb1, 0xc7, 0x29, 0xbc, 0xca, 0xe9, 0x11, 0xc4, 0x5f, 0xac, 0xb0, 0x6b, 0xc3, 0xa2, 0x8c, 0xe4,
	0x11, 0xf7, 0xca, 0xf1, 0x6b, 0xab, 0x19, 0xfe, 0xb4, 0x9e, 0x52, 0xc7, 0x71, 0x5f, 0xfc, 0x8c,
	0x9b, 0x2e, 0xae, 0xbd, 0xbe, 0x85, 0xd8, 0xcb, 0x2b, 0xc4, 0x1e, 0x7b, 0x62, 0x6d, 0x5b, 0x77,
	0x8d, 0xec, 0x57, 0x00, 0xc9, 0x27, 0x34, 0x46, 0x7c, 0xbb, 0x4e, 0x6c, 0x37, 0xff, 0xa0, 0x33,
	0xff, 0xdb, 0x49, 0xf5, 0x13, 0x35, 0xb8, 0x96, 0xa8, 0x7d, 0x7a, 0xa2, 0x1b, 0xd2, 0x13, 0xdf,
	0x94, 0x9e, 0xa4, 0x93, 0x1e, 0xff, 0xde, 0x3b, 0x46, 0x71, 0xf2, 0x15, 0x42, 0x5e, 0x2f, 0xe8,
	0x73, 0x18, 0x8c, 0x45, 0x59, 0xd2, 0xc3, 0x6e, 0x52, 0x47, 0xf7, 0x7a, 0x53, 0xa0, 0x2f, 0x20,
	0x19, 0xaf, 0x84, 0x94, 0xb8, 0xdb, 0xe7, 0xdf, 0x34, 0xea, 0xa9, 0x9c, 0x1c, 0x93, 0xf7, 0xcf,
	0x80, 0x2d, 0x54, 0x55, 0xac, 0xb0, 0x12, 0xdb, 0xb5, 0x2c, 0xe6, 0xf3, 0x72, 0xb3, 0x42, 0x2c,
	0xdd, 0xbe, 0x8f, 0xe4, 0x37, 0x21, 0xf3, 0xb8, 0xf9, 0x11, 0xbc, 0xfa, 0x17, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0xdd, 0xc8, 0x2a, 0x15, 0x04, 0x00, 0x00,
}
